# Problem 4
# Find the largest palindrome made from the product of two 3-digit numbers.

num1 = (100..999).to_a.reverse
num2 = (100..999).to_a.reverse

# Returns array of products generated by all the numbers in the arrays num1 and num2
products = []
num1.each do |num|
  x = 0
  while x < num2.length
    products << num * num2[x]
  x = x +1
  end
end

# Method for checking if a number num is a palindrome
def is_palindrome(num)
  a = num.to_s
  first_half = a.slice(0,a.length/2) 
  second_half = a.reverse.slice(0, a.length/2)
  first_half == second_half 
end

# Returns the first number in array products that is a palindrome
products.sort.reverse.find {|num| is_palindrome(num)}